/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "on-tertiary-fixed": "#2a1700",
        "surface-tint": "#b4c5ff",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-container": "#000f37",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#6800b4",
        "on-tertiary": "#472a00",
        "on-tertiary-container": "#af6f00",
        "outline": "#8e9192",
        "error-container": "#93000a",
        "inverse-primary": "#0053db",
        "tertiary-container": "#1d0f00",
        "on-secondary": "#490080",
        "secondary-container": "#7c03d3",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "surface-container-highest": "#353535",
        "secondary": "#ddb8ff",
        "on-primary-fixed": "#00174b",
        "on-primary": "#002a78",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#3d74fc",
        "inverse-on-surface": "#313030",
        "tertiary": "#ffb95f",
        "secondary-fixed-dim": "#ddb8ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "on-surface-variant": "#c4c7c7",
        "outline-variant": "#444748",
        "on-surface": "#e5e2e1",
        "surface-container": "#20201f",
        "secondary-fixed": "#f0dbff",
        "on-secondary-container": "#dfbcff",
        "primary": "#b4c5ff",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e5e2e1",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#2c0051",
        "surface-variant": "#353535"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
